version: '3.7'

services:
  db:
    image: informaticsmatters/rdkit-cartridge-debian
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - data:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
    restart: always
  genui:
    image: sichom/genui:${DOCKER_IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GENUI_FRONTEND_APP_REPO=${GENUI_FRONTEND_APP_REPO}
        - GENUI_FRONTEND_APP_BRANCH=${GENUI_FRONTEND_APP_BRANCH}
    environment:
      - GENUI_BACKEND_PROTOCOL
      - GENUI_BACKEND_HOST
      - GENUI_BACKEND_PORT
      - DJANGO_SETTINGS_MODULE
      - GENUI_BACKEND_SECRET
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - REACT_APP_GENUI_BACKEND_ROOT_URL=${GENUI_BACKEND_PROTOCOL}://${GENUI_BACKEND_HOST}:${GENUI_BACKEND_PORT}/
      - GENUI_FRONTEND_APP_PATH
      - PUBLIC_URL=${GENUI_FRONTEND_APP_PATH}
    entrypoint: /code/entrypoint.sh
    volumes:
      - media:/code/src/genui/media/
      - static:/code/src/genui/static/
      - frontend:/code/src/genui_gui/build/
      - ./config/nginx/certs/:/etc/certs
    expose:
      - ${GENUI_BACKEND_PORT}
    depends_on:
      - db
      - redis
  celery:
    image: sichom/genui:${DOCKER_IMAGE_TAG}
    environment:
      - DJANGO_SETTINGS_MODULE
      - GENUI_BACKEND_PROTOCOL
      - GENUI_BACKEND_HOST
      - GENUI_BACKEND_PORT
      - GENUI_BACKEND_SECRET
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    command: wait-for-it genui:${GENUI_BACKEND_PORT} -t 3600 -- celery worker -E -A genui --loglevel=info
    volumes:
      - media:/code/src/genui/media/
    depends_on:
      - db
      - redis
      - genui
#  celery-gpu:
#    build: .
#    command: celery worker -c 2 -E -A genui --loglevel=info --queues gpu
#    volumes:
##      - .:/code
#    depends_on:
#      - genui_db
#      - redis
#  celery-beat:
#    build: .
#    command: celery -A proj beat -l info
#    volumes:
#      - .:/code
#    depends_on:
#      - genui_db
#      - redis
  nginx:
    image: nginx:latest
    environment:
      - GENUI_BACKEND_PROTOCOL
      - GENUI_BACKEND_HOST
      - GENUI_BACKEND_PORT
      - GENUI_FRONTEND_APP_PATH
    command: /bin/bash -c "envsubst '$$GENUI_BACKEND_PROTOCOL $$GENUI_BACKEND_HOST $$GENUI_BACKEND_PORT $$GENUI_FRONTEND_APP_PATH' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - media:/usr/share/nginx/html/downloads
      - static:/usr/share/nginx/html/static
      - frontend:/usr/share/nginx/html/app
      - ./config/nginx/:/etc/nginx/conf.d
    depends_on:
      - genui

volumes:
  data:
  media:
  static:
  frontend:

# DOCKER_NET_MTU=1442 must be set so that the app works on the openstack cloud
networks:                                
  default:                               
    driver: bridge                       
    driver_opts:                         
      com.docker.network.driver.mtu: ${DOCKER_NET_MTU}
