version: '3.7'

services:
  db:
    image: informaticsmatters/rdkit-cartridge-debian
    volumes:
      - data:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
    restart: always
  genui:
    image: sichom/genui:${DOCKER_IMAGE_TAG}
    build: .
#      context: .
#      dockerfile: Dockerfile
#      args:
#        - GENUI_BUILD_CONFIG=${GENUI_BUILD_CONFIG}
#        - GENUI_VERSION=${GENUI_VERSION}
    environment:
      - GENUI_BUILD_CONFIG
      - GENUI_VERSION
      - GENUI_BACKEND_SECRET
      - GENUI_BACKEND_PROTOCOL
      - GENUI_BACKEND_HOST
      - GENUI_BACKEND_PORT
      - REACT_APP_GENUI_BACKEND_ROOT_URL=${GENUI_BACKEND_PROTOCOL}://${GENUI_BACKEND_HOST}:${GENUI_BACKEND_PORT}/
    entrypoint: /code/entrypoint.sh
    volumes:
      - media:/code/backend/media/
      - static:/code/backend/static/
      - ./config/nginx/certs/:/etc/certs
    expose:
      - ${GENUI_BACKEND_PORT}
    depends_on:
      - db
      - redis
  celery:
    image: sichom/genui:${DOCKER_IMAGE_TAG}
    environment:
      - GENUI_SKIP_INIT=1
    command: wait-for-it genui:${GENUI_BACKEND_PORT} -t 3600 -- celery worker -E -A genui --loglevel=info
    volumes:
      - media:/code/backend/media/
    depends_on:
      - db
      - redis
      - genui
#  celery-gpu:
#    build: .
#    command: celery worker -c 2 -E -A genui --loglevel=info --queues gpu
#    volumes:
##      - .:/code
#    depends_on:
#      - genui_db
#      - redis
#  celery-beat:
#    build: .
#    command: celery -A proj beat -l info
#    volumes:
#      - .:/code
#    depends_on:
#      - genui_db
#      - redis
  nginx:
    image: nginx:latest
    environment:
      - GENUI_BACKEND_PROTOCOL
      - GENUI_BACKEND_HOST
      - GENUI_BACKEND_PORT
    command: /bin/bash -c "envsubst '$$GENUI_BACKEND_PROTOCOL $$GENUI_BACKEND_HOST $$GENUI_BACKEND_PORT' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d
      - static:/usr/share/nginx/html/static
      - media:/usr/share/nginx/html/downloads
    depends_on:
      - genui

volumes:
  data:
  media:
  static:

# DOCKER_NET_MTU=1442 must be set so that the app works on the openstack cloud
networks:                                
  default:                               
    driver: bridge                       
    driver_opts:                         
      com.docker.network.driver.mtu: ${DOCKER_NET_MTU}
